import Foundation

/// Anglické překlady českých textů v menu, liště a nastavení (klíčem je český text).
public enum Localization {
    public static let supported: [(code: String, title: String)] = [("cs", "Čeština"), ("en", "English")]

    public static func translate(_ cs: String, language: String) -> String {
        guard language == "en" else { return cs }
        if let t = en[cs] ?? enMore[cs] { return t }
        return translatePhrases(cs)
    }

    private static let compiledPhrases: [(NSRegularExpression, String)] = phrases.compactMap { p in
        (try? NSRegularExpression(pattern: p.pattern)).map { ($0, p.replacement) }
    }

    /// Přeloží složený text po frázích (čísla a názvy souborů zůstanou); nic neznámého se nemění.
    public static func translatePhrases(_ text: String) -> String {
        var s = text
        for (re, r) in compiledPhrases {
            s = re.stringByReplacingMatches(in: s, range: NSRange(s.startIndex..., in: s), withTemplate: r)
        }
        return s
    }

    /// Texty, které se záměrně neliší (vlastní názvy).
    public static let untranslated: Set<String> = ["Start", "Server", "Quick View (druhý panel)", "Branch view (všechny podadresáře)"]

    public static let en: [String: String] = [
        "Nový tab": "New Tab", "Zavřít tab": "Close Tab", "Soubor": "File", "Otevřít": "Open", "Hledat soubory…": "Find Files…",
        "Přejmenovat…": "Rename…", "Nový adresář…": "New Folder…", "Nový soubor…": "New File…", "Kopírovat…": "Copy…",
        "Přesunout…": "Move…", "Smazat…": "Delete…", "Smazat trvale…": "Delete Permanently…", "Ověřovat kopie (SHA-256)": "Verify Copies (SHA-256)",
        "Porovnání": "Compare", "Porovnat soubory podle obsahu…": "Compare Files by Content…", "Porovnat adresáře (označit rozdíly)": "Compare Folders (Mark Differences)",
        "Synchronizovat adresáře…": "Synchronize Folders…", "Nástroje": "Tools", "Nastavení…": "Settings…",
        "Importovat nastavení z Total Commanderu…": "Import Settings from Total Commander…", "Hromadné přejmenování…": "Multi-Rename…",
        "Vlastnosti…": "Properties…", "Kontrolní součty…": "Checksums…", "Ověřit kontrolní součty ze souboru": "Verify Checksums from File",
        "Zabalit do archivu…": "Pack to Archive…", "Rozbalit archiv…": "Unpack Archive…", "Otestovat archiv": "Test Archive",
        "Najít duplicitní soubory…": "Find Duplicate Files…", "Kódovat soubory (MIME, UUE, XXE) do druhého panelu…": "Encode Files (MIME, UUE, XXE) to Other Panel…",
        "Dekódovat soubory do druhého panelu…": "Decode Files to Other Panel…", "Rozdělit soubor…": "Split File…", "Spojit soubory (.001)…": "Combine Files (.001)…",
        "Symbolický odkaz do druhého panelu…": "Symbolic Link in Other Panel…", "Pevný odkaz do druhého panelu…": "Hard Link in Other Panel…",
        "Označit": "Mark", "Označit vše": "Mark All", "Zrušit označení": "Unmark All", "Invertovat označení": "Invert Marks",
        "Označit podle masky…": "Mark by Mask…", "Odznačit podle masky…": "Unmark by Mask…", "Označit stejnou příponu": "Mark Same Extension",
        "Uložit výběr": "Save Selection", "Obnovit výběr": "Restore Selection", "Spočítat velikosti adresářů": "Calculate Folder Sizes",
        "Síť": "Network", "Připojit k serveru…": "Connect to Server…", "Odpojit panel od serveru": "Disconnect Panel from Server",
        "Zapomenout připojení": "Forget Connection", "Karty": "Tabs", "Zamknout / odemknout kartu": "Lock / Unlock Tab",
        "Uložit sadu karet…": "Save Tab Set…", "Smazat sadu": "Delete Set", "Oblíbené": "Favorites", "Přidat aktuální adresář": "Add Current Folder",
        "Odebrat": "Remove", "Historie": "History", "Zobrazení": "View", "Skryté soubory": "Hidden Files", "Plný režim": "Full Mode",
        "Stručný režim": "Brief Mode", "Náhledy": "Thumbnails", "Strom adresářů": "Directory Tree", "Sloupce (plný režim)": "Columns (Full Mode)",
        "Panely nad sebou / vedle sebe": "Panels Stacked / Side by Side", "Obnovit": "Refresh", "Rychlý filtr": "Quick Filter",
        "Nadřazený adresář": "Parent Folder", "Zpět": "Back", "Vpřed": "Forward", "Cíl = zdroj": "Target = Source", "Prohodit panely": "Swap Panels",
        "Další tab": "Next Tab", "Předchozí tab": "Previous Tab",
        "příkaz (Enter spustí, „cd cesta“ změní adresář)": "command (Enter runs it, “cd path” changes folder)",
        "F2 Přejmenovat": "F2 Rename", "⌃M Hromadně": "⌃M Multi-Rename", "F3 Zobrazit": "F3 View", "F4 Editovat": "F4 Edit",
        "F5 Kopírovat": "F5 Copy", "F6 Přesunout": "F6 Move", "F7 Nový adresář": "F7 New Folder", "⌥F7 Hledat": "⌥F7 Find", "F8 Smazat": "F8 Delete",
        "Cesta": "Path", "Rychlý filtr (Esc zruší)": "Quick filter (Esc clears)", "Domů": "Home", "Aplikace": "Applications",
        "Obecné": "General", "Zkratky": "Shortcuts", "Tlačítková lišta": "Button Bar", "Start menu": "Start Menu",
        "Uživatelské příkazy": "User Commands", "Přidružení souborů": "File Associations", "Sloupce": "Columns", "Barvy": "Colors", "Pluginy": "Plugins",
        // výchozí tlačítka a Start menu
        "Zobrazit": "View", "Editovat": "Edit", "Kopírovat": "Copy", "Přesunout": "Move", "Nový adresář": "New Folder", "Smazat": "Delete",
        "Hledat": "Find", "Hromadně": "Multi-Rename", "Porovnat": "Compare", "Synchronizovat": "Synchronize", "Server": "Server", "Nastavení": "Settings",
        "Terminál zde": "Terminal Here", "Monitor aktivity": "Activity Monitor", "Systémová nastavení": "System Settings", "Zobrazit ve Finderu": "Reveal in Finder",
        "Terminál": "Terminal",
    ]

    // ===GENERATED===
    /// Další překlady statických textů oken a dialogů.
    public static let enMore: [String: String] = [
        "Upravit text": "Edit text",
        "Blok → doprava": "Block → right",
        "← Blok doleva": "← Block left",
        "Režim úprav – po stisku „Hotovo“ se rozdíly přepočítají": "Edit mode – differences are recalculated when you press “Done”",
        "Zapne psaní přímo do obou souborů; po dokončení se rozdíly přepočítají": "Enables typing directly into both files; differences are recalculated when finished",
        "   Počítadlo [C]: začátek": "   Counter [C]: start",
        "   změněno za posledních": "   modified in the last",
        " (ručně)": " (manual)",
        "(žádné okno)": "(no window)",
        ") není k dispozici.": ") is not available.",
        "Adresář": "Folder",
        "Adresáře": "Folders",
        "Akce": "Action",
        "Archiv je jen pro čtení": "Archive is read-only",
        "Archiv je poškozený": "Archive is damaged",
        "Archiv je v pořádku": "Archive is OK",
        "Archiv nelze uložit do zabalovaného adresáře.": "The archive cannot be saved inside the folder being packed.",
        "Bez konfliktů": "No conflicts",
        "Bez přidružení platí pravidla podle typu: F3 zobrazí text, obrázky, PDF a média v Listeru, dokumenty (Word, Pages, Excel…) přes Quick Look; F4 otevře textové soubory ve zvoleném editoru a ostatní typy v jejich výchozí aplikaci. Příkaz může být aplikace (.app) nebo shellový příkaz s %F.": "Without an association, type-based rules apply: F3 shows text, images, PDF and media in Lister and documents (Word, Pages, Excel…) in Quick Look; F4 opens text files in the chosen editor and other types in their default app. A command can be an app (.app) or a shell command using %F.",
        "Binární soubor": "Binary file",
        "CHYBÍ     ": "MISSING   ",
        "Cesta / sdílená složka:": "Path / share:",
        "Cíl": "Target",
        "Cíl nelze vytvořit": "The target cannot be created",
        "Cíl:": "Target:",
        "Cílový adresář (každý archiv do vlastní složky):": "Target folder (each archive into its own folder):",
        "Cílový adresář:": "Target folder:",
        "Cílový panel je uvnitř archivu nebo na serveru; tato operace sem zapisovat neumí.": "The target panel is inside an archive or on a server; this operation cannot write there.",
        "Další rozdíl ▶︎": "Next difference ▶︎",
        "Další soubor (N)": "Next file (N)",
        "Další část ▶︎": "Next part ▶︎",
        "Datum změny:": "Modified date:",
        "Do koše": "To Trash",
        "Do tohoto formátu archivu nelze zapisovat (lze zip, tar.gz/bz2/xz a 7z). Změňte směr synchronizace.": "This archive format is read-only (zip, tar.gz/bz2/xz and 7z can be written). Change the synchronization direction.",
        "Délka": "Duration",
        "Enter: program / aplikace / příkaz": "Enter: program / app / command",
        "F3 Zobrazit (prázdné = podle typu)": "F3 View (empty = by type)",
        "F4 Editovat (prázdné = podle typu)": "F4 Edit (empty = by type)",
        "FTP/FTPS se otevře v panelu; SMB a WebDAV se připojí jako svazek.": "FTP/FTPS opens in the panel; SMB and WebDAV are mounted as a volume.",
        "Formát:": "Format:",
        "Formát: dd.MM.yyyy HH:mm:ss": "Format: dd.MM.yyyy HH:mm:ss",
        "Hledat soubory": "Find Files",
        "Hledat soubory:": "Find files:",
        "Hledat: text nebo bajty (např. 4D 5A)": "Find: text or bytes (e.g. 4D 5A)",
        "Hledám duplicity…": "Looking for duplicates…",
        "Hledám…": "Searching…",
        "Importovat": "Import",
        "Importovat nastavení z Total Commanderu?": "Import settings from Total Commander?",
        "Jméno (em_…)": "Name (em_…)",
        "Každé Slovo Velké": "Each Word Capitalized",
        "Klíč (SFTP):": "Key (SFTP):",
        "Kontrolní součty": "Checksums",
        "Která šablona se má smazat?": "Which template should be deleted?",
        "Kódování:": "Encoding:",
        "Maska (např. *.txt;*.doc):": "Mask (e.g. *.txt;*.doc):",
        "Maska názvu:": "Name mask:",
        "Maska přípony:": "Extension mask:",
        "Masky souborů": "File masks",
        "Mazat do koše (jinak trvale)": "Delete to Trash (otherwise permanently)",
        "Mění vlastnosti…": "Changing properties…",
        "NESOUHLASÍ ": "MISMATCH ",
        "Nahráno": "Uploaded",
        "Nahráno na server": "Uploaded to server",
        "Nahrát": "Upload",
        "Nahrát ": "Upload ",
        "Nastavení macTC": "macTC Settings",
        "Nastavte kurzor na první část (název.001).": "Place the cursor on the first part (name.001).",
        "Nejsou žádné nalezené soubory na disku (nálezy v archivech se do panelu nedávají).": "There are no found files on disk (hits inside archives are not placed into a panel).",
        "Neplatná oprávnění": "Invalid permissions",
        "Neplatná zkratka": "Invalid shortcut",
        "Neplatné datum": "Invalid date",
        "Neplatný adresář": "Invalid folder",
        "Neplatný cíl": "Invalid target",
        "Neplatný regulární výraz": "Invalid regular expression",
        "Nová složka v archivu": "New Folder in Archive",
        "Nové": "New",
        "Nové připojení": "New connection",
        "Nový adresář na serveru": "New Folder on Server",
        "Nový název": "New name",
        "Nový název:": "New name:",
        "Nový pohled": "New view",
        "Nový příkaz": "New command",
        "Nový soubor": "New File",
        "Název": "Name",
        "Název (lze i vnořený a/b/c):": "Name (nested a/b/c is allowed):",
        "Název (stejný název šablonu nahradí):": "Name (the same name replaces the template):",
        "Název pohledu": "View name",
        "Název sady (stejný název sadu nahradí):": "Set name (the same name replaces the set):",
        "Název souboru se obarví podle první odpovídající masky. Adresáře a označené soubory mají vlastní barvy.": "A file name is colored by the first matching mask. Folders and marked files have their own colors.",
        "Název:": "Name:",
        "Některé položky se nepodařilo synchronizovat": "Some items could not be synchronized",
        "Některé položky se nepodařilo zpracovat": "Some items could not be processed",
        "Některé soubory se nepodařilo dekódovat": "Some files could not be decoded",
        "Některé soubory se nepodařilo smazat": "Some files could not be deleted",
        "Některé soubory se nepodařilo zakódovat": "Some files could not be encoded",
        "Některé změny se nepodařily": "Some changes failed",
        "Některé znaky v něm nejsou. Uložit jako UTF-8?": "Some characters are not available in it. Save as UTF-8?",
        "Obnovit výchozí zkratky": "Restore default shortcuts",
        "Obousměrně (novější vyhrává)": "Two-way (newer wins)",
        "Obrázek": "Image",
        "Obsahující text:": "Containing text:",
        "Oddálit": "Zoom out",
        "Odznačit soubory": "Unmark Files",
        "Offset": "Offset",
        "Oprávnění (osmičkově):": "Permissions (octal):",
        "Otevřeno:": "Accessed:",
        "Otevřít složku pluginů": "Open Plugins Folder",
        "Otočit doleva": "Rotate left",
        "Otočit doprava": "Rotate right",
        "Ověření součtů": "Checksum verification",
        "Ověřuji součty…": "Verifying checksums…",
        "Označit soubory": "Mark Files",
        "Označte dva soubory, nebo nastavte kurzory na soubor v každém panelu.": "Mark two files, or place the cursor on a file in each panel.",
        "Panely nad sebou (místo vedle sebe)": "Panels stacked (instead of side by side)",
        "Parametry": "Parameters",
        "Pevný odkaz": "Hard Link",
        "Plugin": "Plugin",
        "Plugin archiv nerozbalil": "The plugin did not unpack the archive",
        "Podadresáře": "Subfolders",
        "Pohled vyberete v menu Zobrazení › Sloupce. Název je vždy první sloupec.": "Choose a view in View › Columns. The name is always the first column.",
        "Pokračovat": "Continue",
        "Položek:": "Items:",
        "Ponechat obě": "Keep both",
        "Porovnat obsah": "Compare content",
        "Porovnat soubory": "Compare Files",
        "Porovnání binárních souborů": "Binary file comparison",
        "Porovnání selhalo": "Comparison failed",
        "Porovnávám…": "Comparing…",
        "Použijte externí editor (Nastavení › Obecné).": "Use an external editor (Settings › General).",
        "Použijte např. „ctrl+shift+c“, „f5“, „alt+return“.": "Use e.g. “ctrl+shift+c”, “f5”, “alt+return”.",
        "Použít": "Apply",
        "Použít změny i na obsah složky (rekurzivně)": "Apply changes to folder contents too (recursively)",
        "Povolit self-signed certifikát": "Allow self-signed certificate",
        "Provést synchronizaci?": "Run the synchronization?",
        "První velké": "First capital",
        "Předchozí soubor (P)": "Previous file (P)",
        "Předvolby": "Presets",
        "Přehrávač": "Player",
        "Přejmenovat": "Rename",
        "Přejmenovat na serveru": "Rename on Server",
        "Přejmenovat v archivu": "Rename in Archive",
        "Přejmenováno": "Renamed",
        "Přejmenování": "Rename",
        "Přejmenování selhalo": "Rename failed",
        "Přejmenovávám…": "Renaming…",
        "Přejít na soubor": "Go to file",
        "Přejít na:": "Go to:",
        "Přepsat": "Overwrite",
        "Přepsat existující archiv?": "Overwrite the existing archive?",
        "Přepsat starší": "Overwrite older",
        "Přepsat v archivu?": "Overwrite in the archive?",
        "Přepsat vše": "Overwrite all",
        "Přeskočit": "Skip",
        "Přeskočit existující": "Skip existing",
        "Přesunout ": "Move ",
        "Přesunout do koše?": "Move to Trash?",
        "Přesunuto": "Moved",
        "Přesunuto do archivu": "Moved to archive",
        "Přesunuto na server": "Moved to server",
        "Přesunuto ze serveru": "Moved from server",
        "Přiblížit": "Zoom in",
        "Připojení": "Connection",
        "Připojení k serveru selhalo": "Connecting to the server failed",
        "Připojení svazku selhalo": "Mounting the volume failed",
        "Připojit": "Connect",
        "Připojit k serveru": "Connect to Server",
        "Přizpůsobit": "Fit",
        "Přizpůsobit oknu": "Fit to window",
        "Příkaz": "Command",
        "Příkaz (cm_*, em_* nebo program)": "Command (cm_*, em_* or program)",
        "Příkazy: cm_copy, cm_search … (viz záložka Zkratky), em_<název> pro uživatelský příkaz, nebo libovolný program. Parametry: %P zdrojový adresář, %N název pod kurzorem, %S označené, %T cíl, %F plná cesta, %L soubor se seznamem.": "Commands: cm_copy, cm_search … (see the Shortcuts tab), em_<name> for a user command, or any program. Parameters: %P source folder, %N name under the cursor, %S marked, %T target, %F full path, %L list file.",
        "Přípony (čárkou)": "Extensions (comma-separated)",
        "Příznaky:": "Flags:",
        "Původní název": "Original name",
        "Regulární výraz": "Regular expression",
        "Rozbalit": "Unpack",
        "Rozbalit archiv": "Unpack Archive",
        "Rozdělit": "Split",
        "Rozlišovat velikost písmen": "Case sensitive",
        "Rozměry": "Dimensions",
        "SFTP: soubor klíče, např. ~/.ssh/id_ed25519 (volitelné)": "SFTP: key file, e.g. ~/.ssh/id_ed25519 (optional)",
        "Shell se nepodařilo spustit.": "The shell could not be started.",
        "Skryté": "Hidden",
        "Skupina": "Group",
        "Skutečná velikost": "Actual size",
        "Složka": "Folder",
        "Smazat šablonu": "Delete Template",
        "Smazat šablonu…": "Delete Template…",
        "Smazáno": "Deleted",
        "Smazáno na serveru": "Deleted on server",
        "Smazáno z archivu": "Deleted from archive",
        "Směr:": "Direction:",
        "Soubor archivu:": "Archive file:",
        "Soubor je příliš velký pro vestavěný editor": "The file is too large for the built-in editor",
        "Soubor již existuje": "The file already exists",
        "Soubor nelze otevřít": "The file cannot be opened",
        "Soubor nelze přečíst": "The file cannot be read",
        "Soubor nelze přečíst.": "The file cannot be read.",
        "Soubor nelze stáhnout": "The file cannot be downloaded",
        "Soubor usercmd.ini ve stejné složce se načte také.": "A usercmd.ini file in the same folder is loaded too.",
        "Soubor z archivu nelze rozbalit": "The file cannot be unpacked from the archive",
        "Soubory jsou shodné": "The files are identical",
        "Soubory se příliš liší pro zobrazení rozdílů.": "The files differ too much to show differences.",
        "Spojit části": "Combine Parts",
        "Spouštím příkaz…": "Running command…",
        "Spočítat": "Calculate",
        "Spuštění selhalo": "Launch failed",
        "Startovní cesta": "Start path",
        "Stav": "Status",
        "Staženo": "Downloaded",
        "Stáhnout": "Download",
        "Stáhnout ": "Download ",
        "Symbolický odkaz": "Symbolic Link",
        "Synchronizace adresářů": "Folder Synchronization",
        "Terminál (ano/ne)": "Terminal (yes/no)",
        "Terminál:": "Terminal:",
        "Test archivu zrušen": "Archive test cancelled",
        "Textové soubory (F4) otevírat ve vestavěném editoru": "Open text files (F4) in the built-in editor",
        "Uloženo do archivu": "Saved to archive",
        "Uložená:": "Saved:",
        "Uložení selhalo": "Saving failed",
        "Uložit": "Save",
        "Uložit (⌘S)": "Save (⌘S)",
        "Uložit aktuální nastavení…": "Save current settings…",
        "Uložit do souboru": "Save to file",
        "Uložit jako UTF-8": "Save as UTF-8",
        "Uložit jako UTF-8?": "Save as UTF-8?",
        "Uložit levý": "Save left",
        "Uložit pravý": "Save right",
        "Uložit předvolbu": "Save Preset",
        "Uložit předvolbu…": "Save Preset…",
        "Uložit připojení (heslo do Klíčenky)": "Save connection (password in Keychain)",
        "Uložit sadu karet": "Save Tab Set",
        "Uložit změny?": "Save changes?",
        "Uložit šablonu hledání": "Save Search Template",
        "Uživatel:": "User:",
        "V adresáři:": "In folder:",
        "VELKÁ PÍSMENA": "UPPERCASE",
        "Velikost": "Size",
        "Velikost písma:": "Font size:",
        "Velikost písmen:": "Letter case:",
        "Verze": "Version",
        "Vestavěný editor je jen pro text. Použijte Lister (F3) nebo externí aplikaci.": "The built-in editor is for text only. Use Lister (F3) or an external app.",
        "Vlastník / skupina:": "Owner / group:",
        "Vlevo": "Left",
        "Vpravo": "Right",
        "Vrácení zpět selhalo": "Undo failed",
        "Vrátit zpět": "Undo",
        "Vyberte soubory (ne adresáře).": "Select files (not folders).",
        "Vybrané do koše": "Selected to Trash",
        "Vybrané řádky:": "Selected rows:",
        "Vybrat nadbytečné kopie": "Select redundant copies",
        "Vyloučit:": "Exclude:",
        "Vytvořeno": "Created",
        "Vytvořeno částí": "Parts created",
        "Vytvořeno:": "Created:",
        "Vytvoření adresáře selhalo": "Creating the folder failed",
        "Vytvoření odkazu selhalo": "Creating the link failed",
        "Vytvoření souboru selhalo": "Creating the file failed",
        "Vytvořit": "Create",
        "Vytvářím adresář…": "Creating folder…",
        "Výsledky do panelu": "Results to panel",
        "Výška řádku:": "Row height:",
        "Z archivu lze jen kopírovat.": "Only copying out of an archive is possible.",
        "Z archivu lze položky jen kopírovat (rozbalit), ne přesouvat.": "Items can only be copied (unpacked) from an archive, not moved.",
        "Zadejte osmičkově, např. 644.": "Enter in octal, e.g. 644.",
        "Zahodit změny": "Discard changes",
        "Zalamovat řádky": "Wrap lines",
        "Zavřít": "Close",
        "Zkopírovat ": "Copy ",
        "Zkopírováno": "Copied",
        "Zkopírováno do archivu": "Copied to archive",
        "Zkratky (oddělené čárkou, např. ctrl+shift+c, f5)": "Shortcuts (comma-separated, e.g. ctrl+shift+c, f5)",
        "Změna jazyka se projeví po restartu aplikace. Úpravy zkratek platí okamžitě; zkratky v hlavním menu jsou pevné.": "A language change takes effect after restarting the app. Shortcut changes apply immediately; shortcuts in the main menu are fixed.",
        "Změna vlastníka a skupiny vyžaduje práva správce a v macTC není k dispozici.": "Changing owner and group requires administrator rights and is not available in macTC.",
        "Znovu načíst": "Reload",
        "Zobrazit shodné": "Show identical",
        "Zobrazovat skryté soubory": "Show hidden files",
        "Zrcadlit zleva doprava (smazat nadbytečné)": "Mirror left to right (delete extras)",
        "Zrcadlit zprava doleva (smazat nadbytečné)": "Mirror right to left (delete extras)",
        "Zrušeno": "Cancelled",
        "Zrušit": "Cancel",
        "[N] název  [E] přípona  [N1-3] znaky 1–3  [N2,5] od 2. znaku délka 5  [C] počítadlo  [C10+5:3] začátek+krok:číslic  [P] nadřazený adresář  [Y][M][D][h][m][s] datum změny  [d] [t]": "[N] name  [E] extension  [N1-3] characters 1–3  [N2,5] from character 2, length 5  [C] counter  [C10+5:3] start+step:digits  [P] parent folder  [Y][M][D][h][m][s] modification date  [d] [t]",
        "\nArchiv se po synchronizaci znovu vytvoří.": "\nThe archive is recreated after synchronization.",
        "\n[shell skončil – zavřete okno]\n": "\n[shell ended – close the window]\n",
        "\n\n(přerušeno po 60 s)": "\n\n(aborted after 60 s)",
        "až": "to",
        "beze změny": "unchanged",
        "dd.MM.yyyy HH:mm:ss (prázdné = beze změny)": "dd.MM.yyyy HH:mm:ss (empty = unchanged)",
        "dní": "days",
        "dní, starší než": "days, older than",
        "duplicitní název": "duplicate name",
        "ignorovat masky (např. *.tmp;.DS_Store)": "ignore masks (e.g. *.tmp;.DS_Store)",
        "již existuje": "already exists",
        "malá písmena": "lowercase",
        "nahradit čím": "replace with",
        "např. 644": "e.g. 644",
        "např. 644 (prázdné = beze změny)": "e.g. 644 (empty = unchanged)",
        "např. socks5://127.0.0.1:1080, http://proxy:3128 (volitelné)": "e.g. socks5://127.0.0.1:1080, http://proxy:3128 (optional)",
        "načten": "loaded",
        "neplatný znak (/ nebo :)": "invalid character (/ or :)",
        "název pro uložení": "name to save under",
        "počítám…": "calculating…",
        "prohlížeč: ": "viewer: ",
        "prázdné = anonymní": "empty = anonymous",
        "prázdné = domovský adresář": "empty = home folder",
        "prázdný název": "empty name",
        "text v souboru (nepovinné)": "text in file (optional)",
        "ve frontě": "queued",
        "vyloučit masky, např. *.tmp;node_modules": "exclude masks, e.g. *.tmp;node_modules",
        "výchozí": "default",
        "zbývá ": "remaining ",
        "Čeština": "Čeština",
        "číslic": "digits",
        "Řádků": "Lines",
        "Šablony": "Templates",
        "Žádné duplicity": "No duplicates",
        "◀︎ Předchozí rozdíl": "◀︎ Previous difference",
        "◀︎ Předchozí část": "◀︎ Previous part",
        "Stran": "Pages",
        "Atr": "Attr",
        "Přípona": "Extension",
        "Změněno": "Modified",
        "Druh": "Kind",
        "Vlastník": "Owner",
        "Otevřeno": "Accessed",
        "Barva (#rrggbb)": "Color (#rrggbb)",
        "Plugin ": "Plugin ",
        "Schopnosti": "Capabilities",
        "Popis": "Description",
        "Heslo:": "Password:",
        "Server:": "Server:",
        "Port:": "Port:",
        "Typ:": "Type:",
        "Proxy (FTP, SFTP):": "Proxy (FTP, SFTP):",
        "Hledat soubory…": "Find Files…",
        "Hotovo": "Done",
    ]

    /// Frázové úpravy pro složené texty (čísla, názvy souborů); aplikují se po sobě na celý řetězec.
    public static let phrases: [(pattern: String, replacement: String)] = [
        ("(\\d[\\d  ]*) souborů, (\\d[\\d ]*) adresářů", "$1 files, $2 folders"),
        ("(\\d+) souborů", "$1 files"),
        ("(\\d+) soubor(?!ů)", "$1 file"),
        ("(\\d+) položek", "$1 items"),
        ("(\\d+) adresářů", "$1 folders"),
        ("(\\d+) skupin", "$1 groups"),
        ("(\\d+) problémů", "$1 problems"),
        ("(\\d+) dalších", "$1 more"),
        ("(\\d+) archivů", "$1 archives"),
        ("Označeno (\\d+) z (\\d+)", "Marked $1 of $2"),
        ("volných z", "free of"),
        (" nalezeno, prohledáno ", " found, scanned "),
        ("Hotovo: ", "Done: "),
        ("Hledám… nalezeno ", "Searching… found "),
        ("Počet bloků rozdílů: ", "Number of difference blocks: "),
        ("Změní se (\\d+) z (\\d+)", "$1 of $2 will change"),
        ("Rozdílů: (\\d+) · k provedení: (\\d+) \\(kopií: (\\d+), smazání: (\\d+)\\)", "Differences: $1 · to perform: $2 (copies: $3, deletions: $4)"),
        ("Kopírování: (\\d+) files", "Copying: $1 files"),
        (", do koše: (\\d+) files", ", to Trash: $1 files"),
        ("problémů – opravte je před přejmenováním", "problems – fix them before renaming"),
        ("(\\d+) problems – opravte", "$1 problems – fix"),
        (" bude trvale odstraněno z archivu \\(nelze vrátit\\)\\.", " will be permanently removed from the archive (cannot be undone)."),
        (" bude trvale odstraněno \\(nelze vrátit\\)\\.", " will be permanently removed (cannot be undone)."),
        (" položek už v archivu existuje a bude nahrazeno \\(např\\. ", " items already exist in the archive and will be replaced (e.g. "),
        (" už v archivu existuje\\.", " already exists in the archive."),
        ("Smazat z archivu: ", "Delete from archive: "),
        ("Smazat na serveru: ", "Delete on server: "),
        ("Přejmenovat v archivu: ", "Rename in archive: "),
        ("Nová složka v archivu: ", "New folder in archive: "),
        ("Uložit do archivu: ", "Save to archive: "),
        ("Nahrát na server: ", "Upload to server: "),
        ("Stahuji „", "Downloading „"),
        ("Rozbaluji pluginem „", "Unpacking with plugin „"),
        ("Spouštím: ", "Running: "),
        ("Připojuji k ", "Connecting to "),
        ("Připojuji svazek ", "Mounting volume "),
        ("Připojeno: ", "Connected: "),
        ("Připojení selhalo: ", "Connection failed: "),
        ("\\(kód (\\d+)\\)", "(code $1)"),
        ("Rozbalit „", "Unpack „"),
        ("Rozbalit (\\d+) archives", "Unpack $1 archives"),
        ("Rozdělit „", "Split „"),
        ("Rozdělit ", "Split "),
        ("Test archivu ", "Archive test "),
        ("Kontrolní součty ", "Checksums "),
        ("Zabalit do ", "Pack to "),
        ("Zabalit „", "Pack „"),
        ("Zabalit (\\d+) items", "Pack $1 items"),
        ("Kopírovat „", "Copy „"),
        ("Přesunout „", "Move „"),
        ("Stáhnout „", "Download „"),
        ("Nahrát „", "Upload „"),
        ("Kopírovat (\\d+) items", "Copy $1 items"),
        ("Přesunout (\\d+) items", "Move $1 items"),
        ("Stáhnout (\\d+) items", "Download $1 items"),
        ("Nahrát (\\d+) items", "Upload $1 items"),
        ("Rozbalit (\\d+) items", "Unpack $1 items"),
        (" do archivu", " to archive"),
        (" na server", " to server"),
        (" ze serveru", " from server"),
        ("Smazat na serveru\\?", "Delete on server?"),
        ("Smazat z archivu\\?", "Delete from archive?"),
        ("Hromadné přejmenování \\((\\d+) files\\)", "Multi-Rename ($1 files)"),
        ("Hromadné přejmenování \\((\\d+) souborů\\)", "Multi-Rename ($1 files)"),
        ("Duplicitní soubory v ", "Duplicate files in "),
        ("Vlastnosti – ", "Properties – "),
        ("Vlastnosti", "Properties"),
        ("Výsledky hledání \\((\\d+)\\) v ", "Search results ($1) in "),
        ("Terminál – ", "Terminal – "),
        ("Porovnání: ", "Comparison: "),
        ("Porovnání bajtů: ", "Byte comparison: "),
        ("Porovnání adresářů: (\\d+) rozdílů", "Folder comparison: $1 differences"),
        ("Importováno z Total Commanderu: ", "Imported from Total Commander: "),
        ("Tlačítek: (\\d+), uživatelských příkazů: (\\d+), příkazů se zkratkami: (\\d+), oblíbených adresářů: (\\d+)", "Buttons: $1, user commands: $2, commands with shortcuts: $3, favorite folders: $4"),
        ("Sada karet „(.*)“ uložena", "Tab set “$1” saved"),
        ("Uložit změny v souboru „", "Save changes to file „"),
        ("“\\?", "”?"),
        ("Neznámý příkaz „", "Unknown command „"),
        ("Nenalezen plugin se schématem „(.*)“\\. Nainstalované pluginy jsou v Nastavení › Pluginy\\.", "No plugin with scheme “$1” was found. Installed plugins are in Settings › Plugins."),
        ("Archiv rozbalen pluginem „(.*)“ \\(jen pro čtení, dočasná složka\\)", "Archive unpacked by plugin “$1” (read-only, temporary folder)"),
        ("Archiv je v pořádku \\((\\d+) files\\)\\.", "The archive is OK ($1 files)."),
        ("Všech (\\d+) files souhlasí", "All $1 files match"),
        ("Všech (\\d+) souborů souhlasí", "All $1 files match"),
        ("Nesouhlasí nebo chybí: (\\d+) z (\\d+)", "Mismatch or missing: $1 of $2"),
        ("Existuje (\\d+) files se stejným názvem", "$1 files with the same name exist"),
        ("Existuje (\\d+) souborů se stejným názvem", "$1 files with the same name exist"),
        ("Soubor již existuje", "The file already exists"),
        ("Například: ", "For example: "),
        ("Název odkazu v ", "Link name in "),
        ("Název souboru musí končit „", "The file name must end with „"),
        ("Velikost jedné části v MB \\(do ", "Size of one part in MB (to "),
        ("Formát \\(výsledek do ", "Format (result to "),
        ("Algoritmus pro (\\d+) files:", "Algorithm for $1 files:"),
        ("Algoritmus pro (\\d+) souborů:", "Algorithm for $1 files:"),
        ("Výsledek bude uložen do ", "The result will be saved to "),
        ("Adresář „(.*)“ neexistuje\\.", "Folder “$1” does not exist."),
        ("„(.*)“ není adresář\\.", "“$1” is not a folder."),
        ("Není adresář ani archiv: ", "Not a folder or archive: "),
        ("„(.*)“ v archivu už existuje\\.", "“$1” already exists in the archive."),
        ("Soubor „(.*)“ není platný soubor s kontrolními součty\\.", "File “$1” is not a valid checksum file."),
        ("Neplatný regulární výraz: ", "Invalid regular expression: "),
        ("Text nelze uložit v kódování ", "The text cannot be saved in encoding "),
        ("Uloženo · kódování: ", "Saved · encoding: "),
        ("Kódování: ", "Encoding: "),
        ("Offset je mimo soubor \\(velikost (\\d+) bajtů\\)", "Offset is outside the file (size $1 bytes)"),
        ("Nalezeno na offsetu ", "Found at offset "),
        (" bajtů\\)", " bytes)"),
        (" bajtů", " bytes"),
        ("Nenalezeno", "Not found"),
        ("Část (\\d+) z (\\d+) \\(bajty (\\d+)–(\\d+)\\)", "Part $1 of $2 (bytes $3–$4)"),
        (" · část (\\d+) z (\\d+)", " · part $1 of $2"),
        (" · otočeno ", " · rotated "),
        ("zbytečně zabraných ", "wasted: "),
        ("Rozdílných bajtů: ", "Differing bytes: "),
        ("Velikosti se liší; rozdílných nebo chybějících bajtů: ", "Sizes differ; differing or missing bytes: "),
        ("\\(zobrazeno prvních (\\d+) rozdílných řádků\\)", "(first $1 differing rows shown)"),
        ("Soubory jsou shodné \\((.*) bytes\\)\\.", "The files are identical ($1 bytes)."),
        ("Soubory jsou shodné", "The files are identical"),
        ("\\(návratový kód (\\d+)\\)", "(return code $1)"),
        ("Návratový kód (\\d+)", "Return code $1"),
        ("Nepřevedeno \\((\\d+)\\):", "Not converted ($1):"),
        ("V souboru nebylo nalezeno nic, co by šlo převést\\.", "Nothing convertible was found in the file."),
        ("\\n\\n… a (\\d+) more", "\\n\\n… and $1 more"),
        ("přeskočeno: ", "skipped: "),
        ("Zkopírováno: ", "Copied: "),
        ("Přesunuto: ", "Moved: "),
        ("Smazáno: ", "Deleted: "),
        ("Zrušeno: ", "Cancelled: "),
        ("chyb: ", "errors: "),
        ("Staženo: ", "Downloaded: "),
        ("Nahráno: ", "Uploaded: "),
        ("Rozbaleno: ", "Unpacked: "),
        ("Zabaleno: ", "Packed: "),
        ("Do koše: ", "To Trash: "),
        ("Přejmenováno: ", "Renamed: "),
        ("Vytvořeno částí: ", "Parts created: "),
        ("Spojeno: ", "Combined: "),
        ("Přesunout do koše\\?", "Move to Trash?"),
        ("Smazat trvale\\?", "Delete permanently?"),
        ("Do koše:", "To Trash:"),
        ("Mazání: ", "Deleting: "),
        ("Odesílám", "Sending"),
        ("Archiv se po synchronizaci znovu vytvoří\\.", "The archive is recreated after synchronization."),
        ("Z archivu lze jen kopírovat\\.", "Only copying out of an archive is possible."),
        ("Otevírám ve vestavěném Listeru\\.", "Opening in the built-in Lister."),
        ("Vše bylo vráceno do původního stavu\\.", "Everything was restored to its original state."),
        ("Plugin „(.*)“ soubor nezobrazil", "Plugin “$1” did not display the file"),
        ("přerušeno po 60 s", "aborted after 60 s"),
        ("Nepodařilo se", "Failed to"),
        ("soubor nezobrazil", "did not display the file"),
        ("Připojeno", "Connected"),
        ("Hotovo – stiskněte klávesu…", "Done – press any key…"),
        ("„([^„“]*)“", "“$1”"),
    ]
}
